<?php
/**
 * Storage abstraction layer — hybrid local + Google Drive.
 * Single entry point for upload/download/delete across all modules.
 */

require_once __DIR__ . '/db.php';
require_once __DIR__ . '/helpers.php';

/** Module → local upload directory (relative to project root) */
const STORAGE_MODULES = [
    'dokumenty' => 'uploads/dokumenty',
    'revize'    => 'uploads/revize',
    'fond'      => 'uploads/fond',
    'zavady'    => 'uploads/zavady',
    'penb'      => 'uploads/penb',
    'datovka'   => 'uploads/datovka',
    'avatar'    => 'uploads/avatars',
];

/** Module → GDrive subfolder display name */
const STORAGE_GDRIVE_NAMES = [
    'dokumenty' => 'Dokumenty',
    'revize'    => 'Revize',
    'fond'      => 'Fond oprav',
    'zavady'    => 'Závady',
    'penb'      => 'PENB',
    'datovka'   => 'Datovka',
    'avatar'    => 'Avatary',
];

/**
 * Upload file — local + optional GDrive.
 *
 * @param int $svjId SVJ tenant ID (0 = skip GDrive)
 * @param string $module Module name (key in STORAGE_MODULES)
 * @param array $uploadedFile $_FILES entry
 * @param string $localFilename Target filename (already generated by caller)
 * @param string|null $originalName Original user filename
 * @param string|null $subDir Optional subdirectory within module dir (for datovka)
 * @return array ['local_path' => relative, 'gdrive_file_id' => string|null]
 */
function storageUpload(int $svjId, string $module, array $uploadedFile, string $localFilename, ?string $originalName = null, ?string $subDir = null): array
{
    $baseDir = storageLocalDir($module, $subDir);

    if (!move_uploaded_file($uploadedFile['tmp_name'], $baseDir . '/' . $localFilename)) {
        jsonError('Nepodařilo se uložit soubor', 500, 'SAVE_ERROR');
    }

    $relPath = storageRelPath($module, $localFilename, $subDir);
    $mime = $uploadedFile['type'] ?? null;
    $size = $uploadedFile['size'] ?? null;

    return storageTrackAndSync($svjId, $module, $relPath, $originalName ?? basename($uploadedFile['name'] ?? $localFilename), $mime, $size);
}

/**
 * Track + optionally sync an already-saved local file to GDrive.
 * Used by datovka (files extracted from ZFO, not from $_FILES).
 */
function storageTrackFile(int $svjId, string $module, string $localPath, ?string $originalName = null, ?string $mimeType = null, ?int $size = null): array
{
    return storageTrackAndSync($svjId, $module, $localPath, $originalName, $mimeType, $size);
}

/**
 * Internal: track file in DB + upload to GDrive if active.
 */
function storageTrackAndSync(int $svjId, string $module, string $relPath, ?string $originalName, ?string $mime, ?int $size): array
{
    $gdriveFileId = null;
    $gdriveError = null;

    if ($svjId > 0) {
        $db = getDb();
        $db->prepare(
            'INSERT INTO gdrive_files (svj_id, module, local_path, gdrive_name, mime_type, size_bytes)
             VALUES (?, ?, ?, ?, ?, ?)
             ON DUPLICATE KEY UPDATE gdrive_name=VALUES(gdrive_name), mime_type=VALUES(mime_type), size_bytes=VALUES(size_bytes)'
        )->execute([$svjId, $module, $relPath, $originalName, $mime, $size]);

        if (storageIsGdriveActive($svjId)) {
            $gdriveFileId = storageUploadToGdrive($svjId, $module, $relPath, $originalName, $mime);
            if (!$gdriveFileId) {
                $gdriveError = 'Lokální uložení OK, ale nahrání na Google Drive selhalo. Soubor bude synchronizován později.';
            }
        }
    }

    return [
        'local_path'     => $relPath,
        'gdrive_file_id' => $gdriveFileId,
        'gdrive_error'   => $gdriveError,
    ];
}

/**
 * Download file — from local cache or GDrive fallback.
 * Returns absolute path to the file.
 */
function storageDownload(int $svjId, string $localPath): string
{
    $absPath = __DIR__ . '/../' . $localPath;

    if (file_exists($absPath)) {
        return $absPath;
    }

    // Local missing — try GDrive
    if ($svjId > 0 && storageIsGdriveActive($svjId)) {
        $db = getDb();
        $stmt = $db->prepare('SELECT gdrive_file_id FROM gdrive_files WHERE svj_id = ? AND local_path = ?');
        $stmt->execute([$svjId, $localPath]);
        $gdriveId = $stmt->fetchColumn();

        if ($gdriveId) {
            $downloaded = storageDownloadFromGdrive($svjId, $gdriveId, $absPath);
            if ($downloaded) return $absPath;
        }
    }

    return $absPath; // Caller will check file_exists
}

/**
 * Delete file — local + GDrive + tracking.
 */
function storageDelete(int $svjId, string $localPath): void
{
    $absPath = __DIR__ . '/../' . $localPath;
    if (file_exists($absPath)) {
        unlink($absPath);
    }

    if ($svjId <= 0) return;

    $db = getDb();
    $stmt = $db->prepare('SELECT gdrive_file_id FROM gdrive_files WHERE svj_id = ? AND local_path = ?');
    $stmt->execute([$svjId, $localPath]);
    $gdriveId = $stmt->fetchColumn();

    if ($gdriveId) {
        storageDeleteFromGdrive($svjId, $gdriveId);
    }

    $db->prepare('DELETE FROM gdrive_files WHERE svj_id = ? AND local_path = ?')
       ->execute([$svjId, $localPath]);
}

/**
 * Check if GDrive storage is enabled AND Google is connected for this SVJ.
 */
function storageIsGdriveActive(int $svjId): bool
{
    static $cache = [];
    if (isset($cache[$svjId])) return $cache[$svjId];

    $db = getDb();

    // Check svj.gdrive_enabled flag
    $stmt = $db->prepare('SELECT gdrive_enabled FROM svj WHERE id = ?');
    $stmt->execute([$svjId]);
    $enabled = (int) $stmt->fetchColumn();
    if (!$enabled) {
        $cache[$svjId] = false;
        return false;
    }

    // Check if any admin/vybor has Google connected with drive scope
    $userId = storageFindGdriveUser($svjId);
    $cache[$svjId] = ($userId !== null);
    return $cache[$svjId];
}

/**
 * Find admin/vybor user with Google Drive connected for this SVJ.
 */
function storageFindGdriveUser(int $svjId): ?int
{
    $db = getDb();
    $stmt = $db->prepare("
        SELECT gt.user_id FROM google_tokens gt
        JOIN users u ON u.id = gt.user_id
        WHERE gt.svj_id = ? AND u.role IN ('admin', 'vybor')
        AND gt.scopes LIKE '%drive.file%'
        ORDER BY u.role = 'admin' DESC
        LIMIT 1
    ");
    $stmt->execute([$svjId]);
    $uid = $stmt->fetchColumn();
    return $uid ? (int) $uid : null;
}

/**
 * Get or create GDrive folder for module.
 */
function storageEnsureFolder(int $svjId, string $module): ?string
{
    $db = getDb();

    // Check cache
    $stmt = $db->prepare('SELECT gdrive_folder_id FROM gdrive_folders WHERE svj_id = ? AND folder_type = ?');
    $stmt->execute([$svjId, $module]);
    $cached = $stmt->fetchColumn();
    if ($cached) return $cached;

    require_once __DIR__ . '/google_helper.php';

    $userId = storageFindGdriveUser($svjId);
    if (!$userId) return null;

    $service = getGdriveService($userId, $svjId);
    if (!$service) return null;

    // Ensure SVJ root folder
    $svjFolderId = storageEnsureSvjFolder($db, $svjId, $service);
    if (!$svjFolderId) return null;

    // Create module subfolder
    $folderName = STORAGE_GDRIVE_NAMES[$module] ?? ucfirst($module);
    $folderId = storageCreateGdriveFolder($service, $folderName, $svjFolderId);
    if (!$folderId) return null;

    $db->prepare(
        'INSERT INTO gdrive_folders (svj_id, folder_type, gdrive_folder_id)
         VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE gdrive_folder_id = VALUES(gdrive_folder_id)'
    )->execute([$svjId, $module, $folderId]);

    return $folderId;
}

/**
 * Ensure the SVJ-level folder exists on GDrive.
 */
function storageEnsureSvjFolder(PDO $db, int $svjId, Google\Service\Drive $service): ?string
{
    $stmt = $db->prepare('SELECT gdrive_folder_id FROM svj WHERE id = ?');
    $stmt->execute([$svjId]);
    $existing = $stmt->fetchColumn();
    if ($existing) return $existing;

    // Get SVJ name for folder
    $svjStmt = $db->prepare('SELECT nazev, ico FROM svj WHERE id = ?');
    $svjStmt->execute([$svjId]);
    $svj = $svjStmt->fetch(PDO::FETCH_ASSOC);
    $folderName = ($svj['nazev'] ?? 'SVJ') . ($svj['ico'] ? " (ICO: {$svj['ico']})" : '');

    // Ensure root "SVJ Portal" folder
    $rootId = storageEnsureRootFolder($db, $svjId, $service);
    if (!$rootId) return null;

    $folderId = storageCreateGdriveFolder($service, $folderName, $rootId);
    if (!$folderId) return null;

    $db->prepare('UPDATE svj SET gdrive_folder_id = ? WHERE id = ?')->execute([$folderId, $svjId]);
    return $folderId;
}

/**
 * Ensure root "SVJ Portal" folder on GDrive.
 */
function storageEnsureRootFolder(PDO $db, int $svjId, Google\Service\Drive $service): ?string
{
    $stmt = $db->prepare("SELECT gdrive_folder_id FROM gdrive_folders WHERE svj_id = ? AND folder_type = 'root'");
    $stmt->execute([$svjId]);
    $rootId = $stmt->fetchColumn();
    if ($rootId) return $rootId;

    $folderId = storageCreateGdriveFolder($service, 'SVJ Portal', null);
    if (!$folderId) return null;

    $db->prepare(
        "INSERT INTO gdrive_folders (svj_id, folder_type, gdrive_folder_id)
         VALUES (?, 'root', ?) ON DUPLICATE KEY UPDATE gdrive_folder_id = VALUES(gdrive_folder_id)"
    )->execute([$svjId, $folderId]);

    return $folderId;
}

/**
 * Create a folder on Google Drive.
 */
function storageCreateGdriveFolder(Google\Service\Drive $service, string $name, ?string $parentId): ?string
{
    try {
        $meta = new Google\Service\Drive\DriveFile([
            'name'     => $name,
            'mimeType' => 'application/vnd.google-apps.folder',
        ]);
        if ($parentId) {
            $meta->setParents([$parentId]);
        }
        $folder = $service->files->create($meta, ['fields' => 'id']);
        return $folder->id;
    } catch (\Exception $e) {
        error_log('GDrive folder create error: ' . $e->getMessage());
        return null;
    }
}

/**
 * Upload file to GDrive. Updates tracking record.
 */
function storageUploadToGdrive(int $svjId, string $module, string $relPath, ?string $originalName, ?string $mime): ?string
{
    $folderId = storageEnsureFolder($svjId, $module);
    if (!$folderId) return null;

    require_once __DIR__ . '/google_helper.php';
    $userId = storageFindGdriveUser($svjId);
    if (!$userId) return null;

    $service = getGdriveService($userId, $svjId);
    if (!$service) return null;

    $absPath = __DIR__ . '/../' . $relPath;
    if (!file_exists($absPath)) return null;

    try {
        // Použít lokální filename (unikátní hash) jako GDrive název — zamezí kolizím
        $gdriveName = basename($relPath);
        // Přidat původní název do description pro čitelnost
        $description = $originalName ? ('Originál: ' . $originalName) : null;

        $fileMeta = new Google\Service\Drive\DriveFile([
            'name'        => $gdriveName,
            'parents'     => [$folderId],
            'description' => $description,
        ]);
        $result = $service->files->create($fileMeta, [
            'data'       => file_get_contents($absPath),
            'mimeType'   => $mime ?? 'application/octet-stream',
            'uploadType' => 'multipart',
            'fields'     => 'id',
        ]);

        $gdriveId = $result->id;

        $db = getDb();
        $db->prepare(
            'UPDATE gdrive_files SET gdrive_file_id = ?, synced_at = NOW() WHERE svj_id = ? AND local_path = ?'
        )->execute([$gdriveId, $svjId, $relPath]);

        return $gdriveId;
    } catch (\Exception $e) {
        error_log('GDrive upload error: ' . $e->getMessage());
        return null;
    }
}

/**
 * Download file from GDrive, save to local path.
 */
function storageDownloadFromGdrive(int $svjId, string $gdriveFileId, string $absLocalPath): bool
{
    require_once __DIR__ . '/google_helper.php';
    $userId = storageFindGdriveUser($svjId);
    if (!$userId) return false;

    $service = getGdriveService($userId, $svjId);
    if (!$service) return false;

    try {
        $response = $service->files->get($gdriveFileId, ['alt' => 'media']);
        $content = $response->getBody()->getContents();

        $dir = dirname($absLocalPath);
        if (!is_dir($dir)) mkdir($dir, 0750, true);

        file_put_contents($absLocalPath, $content);
        return true;
    } catch (\Exception $e) {
        error_log('GDrive download error: ' . $e->getMessage());
        return false;
    }
}

/**
 * Delete file from GDrive.
 */
function storageDeleteFromGdrive(int $svjId, string $gdriveFileId): void
{
    require_once __DIR__ . '/google_helper.php';
    $userId = storageFindGdriveUser($svjId);
    if (!$userId) return;

    $service = getGdriveService($userId, $svjId);
    if (!$service) return;

    try {
        $service->files->delete($gdriveFileId);
    } catch (\Exception $e) {
        error_log('GDrive delete error: ' . $e->getMessage());
    }
}

/**
 * Sync unsynced local files to GDrive (batch).
 */
function storageSync(int $svjId, string $module, int $limit = 10): array
{
    if (!storageIsGdriveActive($svjId)) {
        return ['synced' => 0, 'remaining' => 0, 'error' => 'GDrive not active'];
    }

    $db = getDb();
    $qb = new WhereBuilder('svj_id', $svjId);
    $qb->addRaw('gdrive_file_id IS NULL');
    if ($module !== 'all') $qb->addWhereAlways('module = ?', $module);

    $stmt = $db->prepare("SELECT id, module, local_path, gdrive_name, mime_type FROM gdrive_files WHERE " . $qb->sql() . " LIMIT ?");
    $qb->bind($stmt);
    $stmt->bindValue(count($qb->params()) + 1, $limit, PDO::PARAM_INT);
    $stmt->execute();
    $files = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $synced = 0;
    foreach ($files as $f) {
        $gid = storageUploadToGdrive($svjId, $f['module'], $f['local_path'], $f['gdrive_name'], $f['mime_type']);
        if ($gid) $synced++;
    }

    $countStmt = $db->prepare("SELECT COUNT(*) FROM gdrive_files WHERE " . $qb->sql());
    $countStmt->execute($qb->params());
    $remaining = (int) $countStmt->fetchColumn();

    return ['synced' => $synced, 'remaining' => $remaining];
}

/**
 * Get sync status per module.
 */
function storageSyncStatus(int $svjId): array
{
    $db = getDb();
    $stmt = $db->prepare(
        'SELECT module,
                COUNT(*) AS total,
                SUM(CASE WHEN gdrive_file_id IS NOT NULL THEN 1 ELSE 0 END) AS synced
         FROM gdrive_files WHERE svj_id = ? GROUP BY module'
    );
    $stmt->execute([$svjId]);
    return $stmt->fetchAll(PDO::FETCH_ASSOC);
}

/* ── Local path helpers ──────────────────────────── */

function storageLocalDir(string $module, ?string $subDir = null): string
{
    $base = STORAGE_MODULES[$module] ?? ('uploads/' . $module);
    $dir = __DIR__ . '/../' . $base;
    if ($subDir) $dir .= '/' . $subDir;
    if (!is_dir($dir)) mkdir($dir, 0750, true);
    return $dir;
}

function storageRelPath(string $module, string $filename, ?string $subDir = null): string
{
    $base = STORAGE_MODULES[$module] ?? ('uploads/' . $module);
    return $subDir ? ($base . '/' . $subDir . '/' . $filename) : ($base . '/' . $filename);
}
